// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2IgWdVkd-hp1ENtpYfe6qXt9ww_erWDw',
    appId: '1:716193954786:web:37350cd925112b57ccd7bb',
    messagingSenderId: '716193954786',
    projectId: 'kencannih',
    authDomain: 'kencannih.firebaseapp.com',
    storageBucket: 'kencannih.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbQXUj2Zcvw_rEUFKyJ5q24AOxfGuA_10',
    appId: '1:716193954786:android:7aff59bf8729f204ccd7bb',
    messagingSenderId: '716193954786',
    projectId: 'kencannih',
    storageBucket: 'kencannih.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMVv7524SIJPtbkvcX0TdObgrXB_mWPRg',
    appId: '1:716193954786:ios:011793063743afe1ccd7bb',
    messagingSenderId: '716193954786',
    projectId: 'kencannih',
    storageBucket: 'kencannih.appspot.com',
    iosBundleId: 'com.example.kencanyuks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMVv7524SIJPtbkvcX0TdObgrXB_mWPRg',
    appId: '1:716193954786:ios:d4e3428e66043ff4ccd7bb',
    messagingSenderId: '716193954786',
    projectId: 'kencannih',
    storageBucket: 'kencannih.appspot.com',
    iosBundleId: 'com.example.kencanyuks.RunnerTests',
  );
}
